<?php

namespace ContainerUwngzjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PUC5TMyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.pUC5TMy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pUC5TMy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'beerRepository' => ['privates', 'App\\Repository\\BeerRepository', 'getBeerRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'sbRepository' => ['privates', 'App\\Repository\\ShopBeerRepository', 'getShopBeerRepositoryService', true],
            'sr' => ['privates', 'App\\Repository\\ShopRepository', 'getShopRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.pUC5TMy.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.pUC5TMy": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'beerRepository' => 'App\\Repository\\BeerRepository',
            'em' => '?',
            'sbRepository' => 'App\\Repository\\ShopBeerRepository',
            'sr' => 'App\\Repository\\ShopRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
