<?php

namespace ContainerUwngzjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBeerTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\BeerType' shared autowired service.
     *
     * @return \App\Form\BeerType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\BeerType'] = new \App\Form\BeerType();
    }
}
