<?php

namespace ContainerUwngzjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBrasserieControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\BrasserieController' shared autowired service.
     *
     * @return \App\Controller\BrasserieController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\BrasserieController'] = $instance = new \App\Controller\BrasserieController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\BrasserieController', $container));

        return $instance;
    }
}
