<?php

namespace ContainerUwngzjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEngageControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EngageController' shared autowired service.
     *
     * @return \App\Controller\EngageController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\EngageController'] = $instance = new \App\Controller\EngageController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\EngageController', $container));

        return $instance;
    }
}
