<?php

namespace ContainerUwngzjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoticeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\NoticeRepository' shared autowired service.
     *
     * @return \App\Repository\NoticeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\NoticeRepository'] = new \App\Repository\NoticeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
