<?php

namespace ContainerUwngzjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShopRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ShopRepository' shared autowired service.
     *
     * @return \App\Repository\ShopRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ShopRepository'] = new \App\Repository\ShopRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
