<?php

namespace ContainerKjvkWjE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0wUP8hwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0wUP8hw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0wUP8hw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contactRepository' => ['privates', 'App\\Repository\\ContactRepository', 'getContactRepositoryService', true],
            'pr' => ['privates', 'App\\Repository\\ProjetRepository', 'getProjetRepositoryService', true],
        ], [
            'contactRepository' => 'App\\Repository\\ContactRepository',
            'pr' => 'App\\Repository\\ProjetRepository',
        ]);
    }
}
