<?php

namespace ContainerKjvkWjE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dqjm0EkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dqjm0Ek' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dqjm0Ek'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'br' => ['privates', 'App\\Repository\\BeerRepository', 'getBeerRepositoryService', true],
            'sbr' => ['privates', 'App\\Repository\\ShopBeerRepository', 'getShopBeerRepositoryService', true],
            'sr' => ['privates', 'App\\Repository\\ShopRepository', 'getShopRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'br' => 'App\\Repository\\BeerRepository',
            'sbr' => 'App\\Repository\\ShopBeerRepository',
            'sr' => 'App\\Repository\\ShopRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
