<?php

namespace ContainerKjvkWjE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IJEYc1mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IJEYc1m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IJEYc1m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'br' => ['privates', 'App\\Repository\\BeerRepository', 'getBeerRepositoryService', true],
            'sr' => ['privates', 'App\\Repository\\ShopRepository', 'getShopRepositoryService', true],
        ], [
            'br' => 'App\\Repository\\BeerRepository',
            'sr' => 'App\\Repository\\ShopRepository',
        ]);
    }
}
