<?php

namespace ContainerKjvkWjE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XeBxr5RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XeBxr5R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XeBxr5R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sr' => ['privates', 'App\\Repository\\ShopRepository', 'getShopRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.XeBxr5R.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.XeBxr5R": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'sr' => 'App\\Repository\\ShopRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
