<?php

namespace ContainerKjvkWjE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBeerTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\BeerType' shared autowired service.
     *
     * @return \App\Form\BeerType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/BeerType.php';

        return $container->privates['App\\Form\\BeerType'] = new \App\Form\BeerType();
    }
}
