<?php

namespace ContainerZRW4s8y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XX4YxnsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XX4Yxns' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XX4Yxns'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'beerRepository' => ['privates', 'App\\Repository\\BeerRepository', 'getBeerRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sbRepository' => ['privates', 'App\\Repository\\ShopBeerRepository', 'getShopBeerRepositoryService', true],
            'sr' => ['privates', 'App\\Repository\\ShopRepository', 'getShopRepositoryService', true],
        ], [
            'beerRepository' => 'App\\Repository\\BeerRepository',
            'em' => '?',
            'sbRepository' => 'App\\Repository\\ShopBeerRepository',
            'sr' => 'App\\Repository\\ShopRepository',
        ]);
    }
}
