<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZRW4s8y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZRW4s8y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZRW4s8y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZRW4s8y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZRW4s8y\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZRW4s8y',
    'container.build_id' => '1c32da7b',
    'container.build_time' => 1674688540,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZRW4s8y');
