<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'Home' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_core-js_modules_es_ar-8c8076.js',
                '/build/Home.js',
            ],
            'css' => [
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_core-js_modules_es_ar-8c8076.css',
                '/build/assets_styles_app_css-assets_styles_app_css.css',
            ],
        ],
        'Other' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_core-js_modules_es_ar-8c8076.js',
                '/build/vendors-node_modules_core-js_modules_es_array_splice_js-node_modules_core-js_modules_es_numbe-3f2dbb.js',
                '/build/Other.js',
            ],
            'css' => [
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_core-js_modules_es_ar-8c8076.css',
                '/build/assets_styles_app_css-assets_styles_app_css.css',
            ],
        ],
    ],
],

]];
